### ISSUE TITLE
Building process doesn't work, missing Makefile

### ISSUE THREAD

**Issue by lindemann09** [expyriment/expyriment-android-runtime#1]
Building process doesn't work for me. I followed strictly the instruction and get an error if building with `./android.py build expyriment_app release`

```
Traceback (most recent call last):
  File "./android.py", line 66, in <module>
    main()
  File "./android.py", line 54, in main
    build.build(iface, args.argument[0], args.argument[1:])
  File "buildlib/build.py", line 353, in build
    "--library", "android-sdk/extras/google/play_apk_expansion/downloader_library",
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Why isn't there a Makefile?

**Comment by fladd** [comment]
Can you attach your configuration file? I'll have a look then.

**Comment by lindemann09** [comment]
make configure build:

```
I'm using Ant to build the package.

Buildfile: build.xml does not exist!
Build failed

The build seems to have failed.
make: *** [build] Error 255
```

**Comment by fladd** [comment]
The problem is that Android API version 8 has to be installed. I included this now in the README.md
